/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SampleReportRouteImport } from './routes/sample-report'
import { Route as OrderRouteImport } from './routes/order'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderStatusRouteImport } from './routes/order.$status'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleReportRoute = SampleReportRouteImport.update({
  id: '/sample-report',
  path: '/sample-report',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/$status',
  path: '/$status',
  getParentRoute: () => OrderRoute,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRouteWithChildren
  '/sample-report': typeof SampleReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/order/$status': typeof OrderStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRouteWithChildren
  '/sample-report': typeof SampleReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/order/$status': typeof OrderStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order': typeof OrderRouteWithChildren
  '/sample-report': typeof SampleReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/order/$status': typeof OrderStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/sample-report'
    | '/sitemap.xml'
    | '/api/webhook'
    | '/order/$status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/sample-report'
    | '/sitemap.xml'
    | '/api/webhook'
    | '/order/$status'
  id:
    | '__root__'
    | '/'
    | '/order'
    | '/sample-report'
    | '/sitemap.xml'
    | '/api/webhook'
    | '/order/$status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRouteWithChildren
  SampleReportRoute: typeof SampleReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-report': {
      id: '/sample-report'
      path: '/sample-report'
      fullPath: '/sample-report'
      preLoaderRoute: typeof SampleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$status': {
      id: '/order/$status'
      path: '/$status'
      fullPath: '/order/$status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof OrderRoute
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrderRouteChildren {
  OrderStatusRoute: typeof OrderStatusRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderStatusRoute: OrderStatusRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRouteWithChildren,
  SampleReportRoute: SampleReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
